name: xsoulspace_analytics
publish_to: none
description: Analytics & crash reporting tools for the app

version: 0.1.0

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  firebase_analytics: ^11.3.3
  firebase_analytics_web: ^0.5.10+2
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  flutter:
    sdk: flutter
  universal_io: ^2.2.2
  xsoulspace_foundation: ^0.0.3

dev_dependencies:
  flutter_lints: ^5.0.0
  lint: ^2.3.0
  xsoulspace_lints: ^0.0.11
